name: Deploy Pipeline

on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t hello-world-image:q3 .

      - name: Run Docker Container
        run: docker run hello-world-image:q3